#!/bin/bash
set -a # this ensures the variables set in the next step are exported to subsequent commands...
source config
$(./role.py)
if [[ $OPENSTACK_INSTALL == "yes" ]] ; then
  echo "Local configuration detected and valid role found"
  echo "Will now commence installation"
else
  echo -e "\e[31mNo local configuration detected or no valid role found"
  echo -e "Will abort installation\e[0m"
  exit
fi
sudo -E bash -ev package.sh && \
sudo -E bash -ev preflight.sh && \
if [[ $MY_ROLE == "controller" ]] ; then
  echo "running controller node setup"
sudo -E bash -ev mysql.sh && \
sudo -E bash -ev keystone.sh && \
sudo -E bash -ev glance.sh && \
sudo -E bash -ev cinder.sh && \
fi && \
sudo -E bash -ev nova.sh && \
sudo -E bash -ev neutron.sh && \
if [[ $MY_ROLE == "compute" ]] ; then
  echo "running compute node setup"
  sudo -E bash -ev compute.sh
fi && \
if [[ $MY_ROLE == "network" ]] ; then
  echo "running network node setup"
  sudo -E bash -ev network.sh
fi && \
echo "all complete... :-)"
